# version: '3.8'

# services:
#   user-service:
#     build: ./user-service
#     ports:
#       - "3001:3000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_HOST=db
#       - DATABASE_USER=root
#       - DATABASE_PASSWORD=password
#       - DATABASE_NAME=userdb

#   product-service:
#     build: ./product-service
#     ports:
#       - "3002:3000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_HOST=db
#       - DATABASE_USER=root
#       - DATABASE_PASSWORD=password
#       - DATABASE_NAME=productdb

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: productdb
#       MYSQL_USER: root
#       MYSQL_PASSWORD: password
#     volumes:
#       - db-data:/var/lib/mysql

# volumes:
#   db-data:
# version: '3.8'

# services:
#   user-service:
#     build:
#       context: ./user-service
#     ports:
#       - "3001:3000"
#     networks:
#       - my-network

#   product-service:
#     build:
#       context: ./product-service
#     ports:
#       - "3002:3000"
#     networks:
#       - my-network

# networks:
#   my-network:
#     driver: bridge

version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=userdb
    networks:
      - my-network

  product-service:
    build:
      context: ./product-service
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=productdb
    networks:
      - my-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: productdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:







