version: '3'
services:
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./frontend/app:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - userdata
      - productdata

  userdata:
    build:
      context: ./userdata
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=userdata-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=userdb
    depends_on:
      - userdata-db

  userdata-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
    volumes:
      - userdata-db:/var/lib/mysql
      - ./sql/userdb.sql:/docker-entrypoint-initdb.d/userdb.sql
    ports:
      - "3307:3306"

  productdata:
    build:
      context: ./productdata
    ports:
      - "5002:5002"
    environment:
      - MYSQL_HOST=productdata-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=productdb
    depends_on:
      - productdata-db

  productdata-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productdb
    volumes:
      - productdata-db:/var/lib/mysql/
      - ./sql/productdb.sql:/docker-entrypoint-initdb.d/productdb.sql
    ports:
      - "3308:3306"

volumes:
  userdata-db:
  productdata-db: